GE-158
cruxinformatics/crux-python pull request #90
Opened 2023-03-29 20:02 UTC by crux-matthijsk

2023-03-29 20:45 UTC, stu-speed commented
Put description in PR title and use same description when you squash and merge

2023-03-29 20:46 UTC, stu-speed requested changes

2023-03-29 20:54 UTC, stu-speed commented on crux/_utils.py
> +        valid_url = [url_base, url_prefix]
is this needed?  should not be different than v2 case

2023-03-29 20:54 UTC, stu-speed commented on crux/models/dataset.py
>              "end_date": None if enddt is None else enddt + timedelta(days=3),
enddt+t should also be converted to isoformat

2023-03-29 21:04 UTC, stu-speed commented on crux/_config.py
> +        log.trace("Setting API prefix-v2 to %s", self.api_prefix_v2)
v1

2023-03-29 21:05 UTC, crux-matthijsk commented on crux/models/dataset.py
>              "end_date": None if enddt is None else enddt + timedelta(days=3),
The tests I did didn't have end_date. I will have to change that and test it another time

2023-03-29 21:11 UTC, crux-matthijsk commented on crux/models/dataset.py
>              "end_date": None if enddt is None else enddt + timedelta(days=3),
changed that

2023-03-29 21:44 UTC, stu-speed commented on crux/_utils.py
> +        valid_url = [url_base, url_prefix]
If it is an issue then why does v2 not have a problem

2023-03-29 21:45 UTC, stu-speed commented on crux/models/dataset.py
> +            "end_date": None if enddt is None else datetime.isoformat(enddt) + timedelta(days=3),
Needs to be datetime.isoformat(enddt+ timedelta(days=3))

2023-03-29 21:49 UTC, stu-speed commented
GE-158 get_latest_files date fix

2023-03-29 21:58 UTC, stu-speed approved these changes

2023-03-30 04:52 UTC, spmistry commented on crux/_config.py
> +            self.api_prefix_v1 = os.environ.get("CRUX_API_PREFIX_V1", "v1/client")
for v2 the default prefix is just v2
should that be made consistent to `v2/client`
[swagger ref](https://api.cruxinformatics.com/v2/client/swagger#/)

2023-03-30 04:54 UTC, spmistry commented on crux/_utils.py
> +        valid_url = [url_base, url_prefix]
quote method is just to encode a url containing special chars
this shouldnt need any special handling for v1 case

2023-03-30 05:00 UTC, spmistry commented on crux/models/dataset.py
> +            "GET", ["v1", "deliveries", self.id, "ids"], headers=headers, params=params
this should be `[v2, client, deliveries, self.id, ids]`
to keep it consistet with existing structure for v2

2023-03-30 05:00 UTC, spmistry commented on crux/models/dataset.py
> +                "GET", ["v1", "deliveries", self.id, delivery_id, "data"], params=params
same here. use  `[v1, client, deliveries, self.id, delivery_id, data]`

2023-03-30 05:01 UTC, spmistry commented on crux/apis.py
> +            "GET", ["v1", "identities", "profile"], model=Identity, headers=headers
use `v1, client` in both endpoints in this file

2023-03-30 05:02 UTC, spmistry requested changes
Pls update the inconsistent behavior across v1 and v2 calls structuring.

2023-03-30 13:00 UTC, stu-speed commented on crux/apis.py
> +            "GET", ["v1", "identities", "profile"], model=Identity, headers=headers
@spmistry  the purpose of the prefix is to expose what the library has access to.  It should only have access to v1/client in the future but during the transition, the client has access to v2 and plat-api prefixes.  The code will be consistent once the transition is complete.

2023-03-30 13:05 UTC, stu-speed commented
@spmistry  v1 and v2 are already inconsistent as there is no v2/client.  That is why the extra code is there.  v2 does not have full support for all api calls and is relying on v1/client as documented in swagger.

2023-03-30 17:03 UTC, spmistry approved these changes

2023-03-30 17:06 UTC, merged